#!/bin/bash
# gmap_put does not copy value

trap "/usr/bin/killall -q -u $USER ./GmapUnit 2>/dev/null" 0 1 2 3 9 15
trap "/bin/rm -f $STDERR" 0 1 2 3 9 15
if [ ! -x ./GmapUnit ]; then
  echo './GmapUnit is missing or not executable'
  echo './GmapUnit is missing or not executable' 1>&2
  exit 1
fi

$BIN/run -stdout=/dev/null -stderr=/dev/null /usr/bin/valgrind --tool=memcheck --leak-check=yes -q --log-file=valgrind.out ./GmapUnit 7 </dev/null
cat valgrind.out
