#!/bin/bash
# 2 Battlefields, 3 Entries

trap "/usr/bin/killall -q -u $USER ./Blotto 2>/dev/null" 0 1 2 3 9 15
trap "/bin/rm -f $STDERR" 0 1 2 3 9 15
if [ ! -x ./Blotto ]; then
  echo './Blotto is missing or not executable'
  echo './Blotto is missing or not executable' 1>&2
  exit 1
fi

$BIN/run -stderr=/dev/null ./Blotto 1 2 <$WHERE/t028.in
