#!/bin/bash
# 4 Battlefields, 3 Entries, Different Scoring

trap "/usr/bin/killall -q -u $USER ./Blotto 2>/dev/null" 0 1 2 3 9 15
trap "/bin/rm -f $STDERR" 0 1 2 3 9 15
if [ ! -x ./Blotto ]; then
  echo './Blotto is missing or not executable'
  echo './Blotto is missing or not executable' 1>&2
  exit 1
fi

$BIN/run -stderr=/dev/null ./Blotto 1 3 4 6 <$WHERE/t040.in
